version: "3"
services:
  log_bot:
    restart: always
    build: ./log_bot
    command: python3 -u ./main.py
    volumes:
      - .:/cleverest_machine
    links:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    depends_on:
      - database

  schedule_bot:
    restart: always
    build: ./schedule_bot
    command: python3 -u ./main.py
    volumes:
      - .:/cleverest_machine
    links:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    depends_on:
      - database
      - log_bot
  
  dashboard:
    restart: always
    build: ./admin
    command: python3 -u ./main.py
    ports:
      - "80:8080"
    links:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    depends_on:
      - database

  database:
    restart: always
    # command: rm /data/db/mongod.lock
    image: mongo:3.0.2
    volumes: 
      - ./.docker/mongodb/data/db/:/data/db/
    
  mongo-express:
    restart: always
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=database
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=b2u
      - ME_CONFIG_BASICAUTH_USERNAME=naboox
      - ME_CONFIG_BASICAUTH_PASSWORD=The2ndlaw
    ports:
      - "8080:8081"
    links:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    depends_on:
      - database