version: "3"
services:
  tlg_bot:
    restart: always
    build: ./tlg_bot
    command: python3 -u ./main.py
    volumes:
      - .:/cleverest_machine
    links:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    depends_on:
      - database

  database:
    restart: always
    # command: rm /data/db/mongod.lock
    image: mongo
    volumes: 
      - ./.docker/mongodb/data/db/:/data/db/
    
  mongo-express:
    restart: always
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=database
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_BASICAUTH_USERNAME=Beka_is_best
      - ME_CONFIG_BASICAUTH_PASSWORD=but_sometimes_Baur_lu4we
    ports:
      - "8080:8081"
    links:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    depends_on:
      - database